#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────
#  FlexDocs (community, single-admin) — One-command setup
#  Run from inside this repo (the API). It clones the web dashboard,
#  generates secrets, and starts nginx + api + web + mongodb via Docker.
#  The single admin is created afterwards via the first-run /setup page.
#  Usage:  ./setup.sh
# ─────────────────────────────────────────────────────────────

# Web dashboard repo (override with: WEB_REPO=<url> ./setup.sh)
WEB_REPO="${WEB_REPO:-https://github.com/khalid-arafa/flexdocs-community-web.git}"

# ── Colors & symbols ──────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'

CHECK="${GREEN}✓${NC}"; CROSS="${RED}✗${NC}"; ARROW="${CYAN}→${NC}"; WARN="${YELLOW}!${NC}"

info()    { printf "  ${ARROW} %b\n" "$*"; }
success() { printf "  ${CHECK} %b\n" "$*"; }
warn()    { printf "  ${WARN} %b\n" "$*"; }
fail()    { printf "\n  ${CROSS} ${RED}%b${NC}\n\n" "$*"; exit 1; }

trap 'printf "\n  ${CROSS} ${RED}${BOLD}Setup failed!${NC} Check the output above.\n\n"; exit 1' ERR

progress() {
  local cur=$1 total=$2 label=$3
  local pct=$(( cur * 100 / total )); local filled=$(( pct / 5 )); local empty=$(( 20 - filled )); local bar
  bar=$(printf '%0.s█' $(seq 1 "$filled" 2>/dev/null) || true)
  bar+=$(printf '%0.s░' $(seq 1 "$empty" 2>/dev/null) || true)
  printf "\r\033[K  ${BLUE}[%s]${NC} %3d%%  %s" "$bar" "$pct" "$label"
}
progress_done() { printf "\r\033[K  ${BLUE}[████████████████████]${NC} 100%%  %s\n" "$1"; }

header() {
  printf "\n${BOLD}${CYAN}"
  printf "  ┌──────────────────────────────────────────┐\n"
  printf "  │     FlexDocs — Single-Admin Setup         │\n"
  printf "  └──────────────────────────────────────────┘${NC}\n\n"
}

TOTAL_STEPS=5; step_num=0
step() { step_num=$((step_num + 1)); printf "\n${BOLD}  [${step_num}/${TOTAL_STEPS}] %b${NC}\n" "$*"; }

# ── 0  Banner ─────────────────────────────────────────────────
header

# ── 1  Prerequisites ─────────────────────────────────────────
step "Checking prerequisites"
missing=()
if ! command -v git &>/dev/null; then missing+=("git"); else success "git $(git --version | awk '{print $3}')"; fi
if ! command -v docker &>/dev/null; then missing+=("docker"); else success "docker $(docker --version | awk '{print $3}' | tr -d ',')"; fi
if docker compose version &>/dev/null 2>&1; then
  COMPOSE="docker compose"; success "docker compose $(docker compose version --short 2>/dev/null || echo '')"
elif command -v docker-compose &>/dev/null; then
  COMPOSE="docker-compose"; success "docker-compose $(docker-compose --version | awk '{print $NF}')"
else missing+=("docker-compose"); fi

if [ ${#missing[@]} -gt 0 ]; then
  printf "\n"; fail "Missing required tools: ${BOLD}${missing[*]}${NC}\n\n  Install: git → https://git-scm.com  •  docker → https://docs.docker.com/get-docker"
fi
if ! docker info &>/dev/null 2>&1; then
  fail "Docker daemon is not running.\n  Start Docker Desktop or run: ${BOLD}sudo systemctl start docker${NC}"
fi
success "Docker daemon is running"

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$PROJECT_DIR"
success "Working in ${DIM}${PROJECT_DIR}${NC}"

# ── 2  Clone the web dashboard ───────────────────────────────
step "Fetching the web dashboard"
if [ -d "web/.git" ]; then
  info "Web already cloned — pulling latest"
  git -C web pull --ff-only --quiet 2>/dev/null || warn "Pull failed (offline?), using existing code"
  success "Web up to date"
else
  [ -d web ] && rm -rf web
  info "Cloning web dashboard..."
  if git clone --quiet "$WEB_REPO" web 2>/dev/null; then
    success "Web cloned"
  else
    fail "Failed to clone web from ${WEB_REPO}\n  Check your connection / repo access, or set WEB_REPO=<url>."
  fi
fi

if [ ! -f web/Dockerfile ]; then
  cat > web/Dockerfile <<'WEOF'
FROM node:18-alpine
WORKDIR /app
COPY . .
RUN npm install
CMD ["npm", "run", "dev"]
WEOF
  success "Web Dockerfile created"
fi

# ── 3  Generate configuration ────────────────────────────────
step "Generating configuration"
gen_secret() { openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64; }

MONGO_USER="flexdocs_admin"

if [ ! -f ./.env ]; then
  MONGO_PASS="$(gen_secret | tr -d '/+=' | head -c 24)"
  JWT_SECRET="$(gen_secret)"
  ENCRYPTION_KEY="$(gen_secret)"
  SETUP_TOKEN="$(gen_secret | tr -d '/+=' | head -c 40)"

  cat > ./.env <<ENVEOF
# ── Generated by FlexDocs setup — $(date -Iseconds) ──
JWT_SECRET="${JWT_SECRET}"
ENCRYPTION_KEY="${ENCRYPTION_KEY}"

# First-run admin setup token (used once at http://api.localhost/setup)
SETUP_TOKEN="${SETUP_TOKEN}"

# MongoDB (matches docker-compose)
MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/?authSource=admin
MONGO_USER=${MONGO_USER}
MONGO_PASS=${MONGO_PASS}

# CORS
ALLOWED_ORIGINS=http://admin.localhost,http://localhost:3000

# Rate limiting
RATE_LIMIT_API_MAX=300
RATE_LIMIT_AUTH_MAX=30
RATE_LIMIT_ANON_MAX=10

# App info
FROM_NAME=FlexDocs
APP_NAME=FlexDocs
ENVEOF
  success ".env created with secure secrets"
else
  SETUP_TOKEN=$(grep -oP '(?<=^SETUP_TOKEN=)"?[^"]*' ./.env 2>/dev/null | tr -d '"' || echo "")
  warn ".env already exists — keeping it"
fi

if [ ! -f web/.env ]; then
  printf 'NEXT_PUBLIC_API_URL=http://api.localhost\n' > web/.env
  success "web/.env created"
else
  warn "web/.env already exists — keeping it"
fi

# ── 4  Build & start ─────────────────────────────────────────
step "Building and starting containers"
info "This may take a few minutes on first run..."
printf "\n"

progress 1 4 "Pulling MongoDB..."
$COMPOSE pull mongodb --quiet 2>/dev/null || true
progress 1 4 "Pulling MongoDB...done"

progress 2 4 "Building API image..."
if ! $COMPOSE build --quiet api 2>/dev/null; then
  printf "\n"; warn "Quiet build failed, retrying with output..."; $COMPOSE build api || fail "Failed to build API image"
fi

progress 3 4 "Building Web image..."
if ! $COMPOSE build --quiet web 2>/dev/null; then
  printf "\n"; warn "Quiet build failed, retrying with output..."; $COMPOSE build web || fail "Failed to build Web image"
fi

progress 4 4 "Building Nginx image..."
$COMPOSE build --quiet nginx 2>/dev/null || $COMPOSE build nginx || fail "Failed to build Nginx image"
progress_done "All images built"

printf "\n"; info "Starting services..."
$COMPOSE up -d 2>/dev/null || $COMPOSE up -d || fail "Failed to start containers"

printf "\n"; info "Waiting for services to come online..."
wait_for_service() {
  local container=$1 max=$2; local i=0
  while [ $i -lt "$max" ]; do
    if docker inspect --format='{{.State.Running}}' "$container" 2>/dev/null | grep -q true; then return 0; fi
    i=$((i + 1)); sleep 1
  done
  return 1
}
for svc in flexdocs-mongodb flexdocs-api flexdocs-web flexdocs-nginx; do
  label=$(echo "$svc" | sed 's/flexdocs-//')
  if wait_for_service "$svc" 30; then success "${label} is running"; else warn "${label} may still be starting (check: docker logs ${svc})"; fi
done

# ── 5  Done ───────────────────────────────────────────────────
step "Setup complete!"
printf "\n  ${BOLD}${GREEN}FlexDocs is ready!${NC}\n\n"
printf "  ${BOLD}${YELLOW}First-run admin setup (open this once):${NC}\n"
if [ -n "${SETUP_TOKEN:-}" ]; then
  printf "    ${CYAN}http://api.localhost/setup?token=${SETUP_TOKEN}${NC}\n\n"
else
  printf "    ${CYAN}http://api.localhost/setup${NC}  ${DIM}(SETUP_TOKEN is in ./.env)${NC}\n\n"
fi
printf "  ${BOLD}Dashboard:${NC}   http://admin.localhost\n"
printf "  ${BOLD}API health:${NC}  http://api.localhost/health\n\n"
printf "  ${DIM}Manage:${NC}\n"
printf "    ${DIM}Stop:    cd ${PROJECT_DIR} && ${COMPOSE} down${NC}\n"
printf "    ${DIM}Start:   cd ${PROJECT_DIR} && ${COMPOSE} up -d${NC}\n"
printf "    ${DIM}Logs:    cd ${PROJECT_DIR} && ${COMPOSE} logs -f${NC}\n"
printf "    ${DIM}Rebuild: cd ${PROJECT_DIR} && ${COMPOSE} up -d --build${NC}\n\n"
printf "  ${CHECK} ${BOLD}${GREEN}Done!${NC} Create your admin via the setup link above, then sign in at the dashboard.\n\n"
